# Generated by Django 5.1.5 on 2025-01-28 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Имя персонажа')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('power', models.IntegerField(null=True, verbose_name='Сила')),
                ('dexterity', models.IntegerField(null=True, verbose_name='Ловкость')),
                ('endurance', models.IntegerField(null=True, verbose_name='Выносливость')),
                ('wisdom', models.IntegerField(null=True, verbose_name='Мудрость')),
                ('intellect', models.IntegerField(null=True, verbose_name='Интеллект')),
                ('charisma', models.IntegerField(null=True, verbose_name='Харизма')),
                ('image', models.ImageField(blank=True, null=True, upload_to='personages', verbose_name='Изображение персонажа')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Раса')),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя игрока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gamers', verbose_name='Фото игрока')),
                ('personages', models.ManyToManyField(to='mysite.personage', verbose_name='Персонажи')),
            ],
        ),
        migrations.AddField(
            model_name='personage',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.race', verbose_name='Раса'),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер выпуска')),
                ('title', models.CharField(max_length=50, verbose_name='Название выпуска')),
                ('url', models.URLField(max_length=150, verbose_name='Ссылка')),
                ('gamers', models.ManyToManyField(to='mysite.gamer', verbose_name='Игроки')),
                ('personages', models.ManyToManyField(to='mysite.personage', verbose_name='Персонажи')),
            ],
        ),
    ]
