# Generated by Django 5.1.5 on 2025-01-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_storyline_release_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='releases', verbose_name='Афиша'),
        ),
    ]
