# Generated by Django 5.1.5 on 2025-01-28 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_release_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personage',
            name='gamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personages_list', to='mysite.gamer', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='personages',
            field=models.ManyToManyField(related_name='gamers', to='mysite.personage', verbose_name='Персонажи'),
        ),
    ]
