# Generated by Django 5.1.5 on 2025-02-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_gamer_personages'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='annotation',
            field=models.TextField(blank=True, verbose_name='Аннотация'),
        ),
    ]
