# Generated by Django 5.1.6 on 2025-02-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_release_annotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamer',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='personage',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Раса', 'verbose_name_plural': 'Расы'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'verbose_name': 'Выпуск', 'verbose_name_plural': 'Выпуски'},
        ),
        migrations.AlterModelOptions(
            name='storyline',
            options={'verbose_name': 'Сюжетная линия', 'verbose_name_plural': 'Сюжетные линии'},
        ),
        migrations.AlterField(
            model_name='release',
            name='url',
            field=models.URLField(blank=True, max_length=150, verbose_name='Ссылка'),
        ),
    ]
