# Generated by Django 5.1.6 on 2025-02-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_gamer_options_alter_personage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
