# Generated by Django 5.1.6 on 2025-02-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_personage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personage',
            name='image',
            field=models.ImageField(null=True, upload_to='personages', verbose_name='Изображение персонажа'),
        ),
    ]
