# Generated by Django 5.1.6 on 2025-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_personage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='personages', verbose_name='Изображение персонажа'),
        ),
    ]
