# Generated by Django 5.1.6 on 2025-02-17 09:25

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_personage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=mysite.models.picture_upload_to, verbose_name='Рисунок')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Описание фото')),
                ('personage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.personage', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Рисунок',
                'verbose_name_plural': 'Рисунки',
            },
        ),
    ]
