# Generated by Django 5.1.6 on 2025-02-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='in_release',
            field=models.BooleanField(default=False, verbose_name='Показывать в выпусках'),
        ),
    ]
