# Generated by Django 5.2.7 on 2026-05-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='in_release',
            field=models.BooleanField(default=False, verbose_name='Показывать в выпусках'),
        ),
        migrations.AddField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
