# Generated by Django 5.1.6 on 2025-02-17 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.release', verbose_name='Выпуск'),
        ),
    ]
