# Generated by Django 5.1.6 on 2025-02-18 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_picture_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='personage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.personage', verbose_name='Персонаж'),
        ),
    ]
