# Generated by Django 5.1.6 on 2025-02-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_picture_personage'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='in_release',
            field=models.BooleanField(default=False),
        ),
    ]
